name = "spotless"
version = "1.0.0"
target = "javascript"
description = "Instant OAuth integration for personal projects."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "spotless" }
links = [{ title = "Website", href = "https://spotless.run" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
midas = ">= 1.4.1 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
